image: node:latest

stages:
  - build
  - test

before_script:
  - npm install

build:
  stage: build
#  cache:
#    key: "$CI_COMMIT_REF_NAME:node_modules"
#    paths:
#      - node_modules/
#    policy: push
  script:
#    - npm install
    - npm run build
  only:
    - master
    - merge_requests
    - tags

audit:
  stage: build
  allow_failure: true
  script:
    - npm audit
  only:
    - master
    - merge_requests

prettier:
  stage: test
#  cache:
#    key: "$CI_COMMIT_REF_NAME:node_modules"
#    paths:
#      - node_modules/
#    policy: pull
  script:
    - npm run prettier:ci
  only:
    - master
    - merge_requests
    - tags

lint:
  stage: test
#  cache:
#    key: "$CI_COMMIT_REF_NAME:node_modules"
#    paths:
#      - node_modules/
#    policy: pull
  script:
    - npm run lint:ci
  only:
    - master
    - merge_requests
    - tags

test-unit:
  stage: test
#  cache:
#    key: "$CI_COMMIT_REF_NAME:node_modules"
#    paths:
#      - node_modules/
#    policy: pull
  script:
    - npm run test:ci
  coverage: '/Statements\s*:\s*(\d+(?:\.\d+)?)%/'
  only:
    - master
    - merge_requests
    - tags

test-integration:
  stage: test
#  cache:
#    key: "$CI_COMMIT_REF_NAME:node_modules"
#    paths:
#      - node_modules/
#    policy: pull
  script:
    - npm run test:integration:ci
  only:
    - master
    - merge_requests
    - tags

test-functional:
  stage: test
#  cache:
#    key: "$CI_COMMIT_REF_NAME:node_modules"
#    paths:
#      - node_modules/
#    policy: pull
  variables:
    AMQP_HOST: rabbitmq
  services:
    - name: rabbitmq:3
      alias: rabbitmq
  script:
    - npm run test:functional:ci
  only:
    - master
    - merge_requests
    - tags
